# Connexion à la base de données Supabase
[postgres]
host = "db.ookqqfxklaucvfvlbmge.supabase.co"
port = 5432
database = "postgres"
user = "postgres"
password = "Cisseoumar14$"
sslmode = "require"

[supabase]
url = "https://ookqqfxklaucvfvlbmge.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9va3FxZnhrbGF1Y3ZmdmxibWdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MTg1NzQsImV4cCI6MjA2MDI5NDU3NH0.M5iHbjRcnyFY_8qAOg8my6aD3qO85IJEV8FPa4CUiaY"

# Configuration Google Sheets
[google]
credentials = '''
{
  "type": "service_account",
  "project_id": "cirt-ivoiriens-siberie",
  "private_key_id": "57333174304-i63u32onhn0nfa55mkq2eouoj3n1ls6a",
  "private_key": "-----BEGIN PRIVATE KEY-----\\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC7VJTUt9Us8cKj\\nMzEfYyjiWAO1Kbrp+RaUFPtSX3WbYqQqMmgAlwxq+NTmS4LMwxr8mJE8lRbu7b1F\\nLCPYcOUbA1q8tqJu4Vm8dQ0BQCPeVRVn8XKWCgDmGYpajt0ls3BAdRvW/ITe0v4b\\n1BxiI0Q73k0+8YKWwq5gYO8wx0G3x3rF1cHwKz4LgP9dlZpzqyTDQ+PDsauRaLRD\\nVJm2ZJ/x0z6Ux+HIeG+Qm6MhOqMyJ0+5jWFdmkZ2dFfqZjFKx7dZexwTEA+Y5aJT\\nXbr6XkQKb3VNvW8d4CDJYTrPc7J+xh0l94+5QJxU9Xyowf+TMmDpXtIUqW5YrdjZ\\nVYD3Zg5zHCHByMcLciKj+EViwN+giUIbQmyQ2g==\\n-----END PRIVATE KEY-----\\n",
  "client_email": "cirt-ivoiriens-siberie@cirt-ivoiriens-siberie.iam.gserviceaccount.com",
  "client_id": "57333174304-i63u32onhn0nfa55mkq2eouoj3n1ls6a",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/cirt-ivoiriens-siberie%40cirt-ivoiriens-siberie.iam.gserviceaccount.com"
}
'''
sheets_id = "11ucmdeReXYeAD4phDTJSyq_5ELnADZlUQpDZhH43Gk8"

[google_sheets]
id = "11ucmdeReXYeAD4phDTJSyq_5ELnADZlUQpDZhH43Gk8" 